### PR TITLE
Use latest development release

### PR DESCRIPTION
**Pull request by chiroptical**
Here is an initial stab at upgrading to the latest release. I don't have any OSX devices to test this on.

### CODE REVIEW

**Comment by chiroptical** [comment]
I don't think this really makes sense to merge. I guess you would want to update this with `nix flake update` by overloading the unison url. I need to mess with this though.

**Comment by ceedubs** [comment]
@chiroptical thanks for giving this a go!

This is something that I've come to a few times and am really not sure how to handle. The `latest` in the URL is a dev build that is replaced by every commit to trunk. This doesn't really play nicely with Nix, as the URL is not stable and the content hash will change multiple times a day.

We could move this to the flake input, but I'm not sure how to get around https://github.com/NixOS/nix/issues/7083, other than changing the way that the releases are published. Changing the way that the releases are published probably isn't totally off the table, but I don't know how much it helps; we'd still be needing to run an update on the flake lock file really often.

@tstat do you have any ideas on what should be done?

**Comment by ceedubs** [comment]
I still don't have a great solution in mind for this, but ucm releases are starting to happen on a 2 week cadence, so this is probably less of a concern than it used to be.

**Comment by ceedubs** [comment]
I'm going to go ahead and close this out. Releases have regularly been happening every 2 weeks, so I don't think that there's much of a need for development builds through Nix (which is kind of against the nature of Nix).

There's still the option to use the dev shell to `stack build` ucm if someone really wants the latest code.

Thanks a lot for submitting this, @chiroptical! Let me know if you have any concerns.

**Pull request closed without merging**
