### PR TITLE
add home-manager instructions

### PR DESCRIPTION
**Pull request by bbarker**

### CODE REVIEW

**Review by ceedubs — APPROVED** [review]
Thank you! LGTM.

One minor note/question: isn't this mostly about how to use it from a Nix flake? Unless I'm mistaken the note at the bottom about `home.nix` is the only part specific to home-manager.

**Comment by bbarker** [comment]
That's a good point - I'll admit I don't have a great deal of experience with flakes or overlays, so I wasn't aware if it generalized in a useful way. But I suppose it should.

**Comment by bbarker** [comment]
so I could change it to be about flakes and just add a comment for home-manager

**Comment by ceedubs** [comment]
If I'm honest I'm not sure how much value exposing an overlay is bringing to the table. But yeah I think that you could do that! I also think that it's useful in its current form, so I'm going to merge.

**Pull request merged**
